/**
 * Word timings in, an ASS subtitle file out.
 *
 * Captions are grouped into short chunks and drawn one word at a time so the
 * word currently being spoken is highlighted, which is what makes short-form
 * captions readable at arm's length.
 */

import type { Cue, SpokenLine } from "./types";

export const CAPTION_DEFAULTS = {
  maxWords: 3,
  maxChars: 16,
  /** A pause longer than this starts a new chunk. */
  pauseBreak: 0.45,
  /** Chunks shorter than this are held a little longer so they can be read. */
  minDuration: 0.5,
  /** How long a chunk may linger past its last word to cover a short pause. */
  maxHold: 0.9,
};

export function groupWords(lines: SpokenLine[], options = CAPTION_DEFAULTS): Cue[] {
  const cues: Cue[] = [];

  for (const line of lines) {
    let current: Cue | null = null;

    for (const word of line.words) {
      const wouldOverflow =
        current !== null &&
        (current.words.length >= options.maxWords ||
          current.words.map((w) => w.text).join(" ").length + word.text.length + 1 >
            options.maxChars ||
          word.start - current.end > options.pauseBreak);

      if (current === null || wouldOverflow) {
        current = { start: word.start, end: word.end, words: [word] };
        cues.push(current);
      } else {
        current.words.push(word);
        current.end = word.end;
      }
    }
  }

  // Hold each chunk into the pause that follows it, so captions do not blink
  // out between words or between lines.
  for (let i = 0; i < cues.length; i += 1) {
    const cue = cues[i];
    const next = cues[i + 1];
    const natural = Math.max(cue.end, cue.start + options.minDuration);
    const ceiling = next ? next.start : natural + 0.35;
    cue.end = Math.max(natural, Math.min(ceiling, cue.end + options.maxHold));
    if (cue.end <= cue.start) cue.end = cue.start + 0.2;
  }

  return cues;
}

/** ASS timestamps are H:MM:SS.cc */
export function assTime(seconds: number): string {
  const clamped = Math.max(0, seconds);
  const hours = Math.floor(clamped / 3600);
  const minutes = Math.floor((clamped % 3600) / 60);
  const secs = Math.floor(clamped % 60);
  const centis = Math.floor((clamped - Math.floor(clamped)) * 100);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${hours}:${pad(minutes)}:${pad(secs)}.${pad(centis)}`;
}

/** ASS colours are &HAABBGGRR, i.e. reversed channels with an alpha byte. */
export function assColor(hex: string, alpha = 0): string {
  const clean = hex.replace("#", "").trim();
  const r = clean.slice(0, 2);
  const g = clean.slice(2, 4);
  const b = clean.slice(4, 6);
  const a = alpha.toString(16).padStart(2, "0");
  return `&H${a}${b}${g}${r}`.toUpperCase();
}

/** Braces and backslashes are override syntax in ASS, so they cannot survive. */
export function escapeAss(text: string): string {
  return text
    .replace(/\\/g, "/")
    .replace(/\{/g, "(")
    .replace(/\}/g, ")")
    .replace(/[\r\n]+/g, " ")
    .trim();
}

export function wrapText(text: string, maxChars: number, maxLines: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    if (current && `${current} ${word}`.length > maxChars) {
      lines.push(current);
      current = word;
      if (lines.length === maxLines) break;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current && lines.length < maxLines) lines.push(current);

  if (lines.length === maxLines) {
    const consumed = lines.join(" ").split(/\s+/).length;
    if (consumed < words.length) lines[maxLines - 1] = `${lines[maxLines - 1]}…`;
  }
  return lines;
}

export interface AssOptions {
  cues: Cue[];
  title: string;
  duration: number;
  accent: string;
  width?: number;
  height?: number;
  fontName?: string;
  captionSize?: number;
}

export function buildAss(options: AssOptions): string {
  const width = options.width ?? 1080;
  const height = options.height ?? 1920;
  const font = options.fontName ?? "Anton";
  const captionSize = options.captionSize ?? 118;
  const white = assColor("#FFFFFF");
  const accent = assColor(options.accent);
  const outline = assColor("#0A0A0A");
  const shadow = assColor("#000000", 0x60);

  const header = [
    "[Script Info]",
    "; Generated by Short-clips",
    "ScriptType: v4.00+",
    `PlayResX: ${width}`,
    `PlayResY: ${height}`,
    "WrapStyle: 0",
    "ScaledBorderAndShadow: yes",
    "YCbCr Matrix: TV.709",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour," +
      " Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline," +
      " Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    `Style: Caption,${font},${captionSize},${white},${accent},${outline},${shadow},` +
      `0,0,0,0,100,100,1,0,1,10,5,2,80,80,${Math.round(height * 0.42)},1`,
    `Style: Title,${font},64,${white},${white},${outline},${shadow},` +
      `0,0,0,0,100,100,2,0,1,7,3,8,100,100,${Math.round(height * 0.065)},1`,
    `Style: Bar,${font},40,${accent},${accent},${accent},${accent},` +
      "0,0,0,0,100,100,0,0,1,0,0,7,0,0,0,1",
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ];

  const events: string[] = [];

  // A progress bar drawn as a rectangle that is revealed by an animated clip.
  const barHeight = 12;
  const barTop = height - barHeight;
  const durationMs = Math.round(options.duration * 1000);
  events.push(
    `Dialogue: 0,${assTime(0)},${assTime(options.duration)},Bar,,0,0,0,,` +
      `{\\an7\\pos(0,${barTop})\\bord0\\shad0\\alpha&H30&` +
      `\\clip(0,${barTop},0,${height})\\t(0,${durationMs},\\clip(0,${barTop},${width},${height}))` +
      `\\p1}m 0 0 l ${width} 0 ${width} ${barHeight} 0 ${barHeight}{\\p0}`,
  );

  const titleLines = wrapText(escapeAss(options.title), 30, 2);
  if (titleLines.length > 0) {
    events.push(
      // Visible from the very first frame, which the player uses as the poster.
      `Dialogue: 0,${assTime(0)},${assTime(options.duration)},Title,,0,0,0,,` +
        `{\\fad(0,350)}${titleLines.join("\\N")}`,
    );
  }

  for (const cue of options.cues) {
    const texts = cue.words.map((word) => escapeAss(word.text).toUpperCase());

    cue.words.forEach((word, index) => {
      const start = index === 0 ? cue.start : word.start;
      const end = index === cue.words.length - 1 ? cue.end : cue.words[index + 1].start;
      if (end <= start) return;

      const highlighted = texts
        .map((text, position) =>
          position === index ? `{\\c${accent}}${text}{\\c${white}}` : text,
        )
        .join(" ");

      // The chunk pops in once, then only the highlight moves between words.
      const first = index === 0;
      const last = index === cue.words.length - 1;
      const fade = first && last ? "\\fad(70,70)" : first ? "\\fad(70,0)" : last ? "\\fad(0,70)" : "";
      const pop = first ? "\\fscx92\\fscy92\\t(0,110,\\fscx100\\fscy100)" : "";
      const tags = `${fade}${pop}`;

      events.push(
        `Dialogue: 1,${assTime(start)},${assTime(end)},Caption,,0,0,0,,` +
          `${tags ? `{${tags}}` : ""}${highlighted}`,
      );
    });
  }

  return `${[...header, ...events].join("\n")}\n`;
}
